[evaluator]
endpoint = "http://127.0.0.1:18081"
cmd = "python src/evaluator/server.py --host 127.0.0.1 --port 18081"

[agent_under_test]
endpoint = "http://127.0.0.1:18080"
cmd = "python src/track_1_agent_coroutine_under_test/server.py --host 127.0.0.1 --port 18080 --model-provider nebius --agent-llm openai/gpt-oss-120b-fast --skill car_domain_120b.md"

[config]
num_trials = 1
task_split = "train"
tasks_base_num_tasks = 0
tasks_hallucination_num_tasks = 9
tasks_hallucination_task_id_filter = [
  "hallucination_4",
  "hallucination_32",
  "hallucination_38",
  "hallucination_40",
  "hallucination_60",
  "hallucination_82",
  "hallucination_88",
  "hallucination_90",
  "hallucination_94",
]
tasks_disambiguation_num_tasks = 0
max_steps = 50

user_model = "gpt-4.1-mini"
user_provider = "openai"
user_thinking = false

policy_evaluator_model = "gpt-4.1-mini"
policy_evaluator_provider = "openai"
