[evaluator]
endpoint = "http://127.0.0.1:18081"
cmd = "python src/evaluator/server.py --host 127.0.0.1 --port 18081"

[agent_under_test]
endpoint = "http://127.0.0.1:18080"
cmd = "python src/track_1_agent_coroutine_under_test/server.py --host 127.0.0.1 --port 18080 --model-provider cerebras --agent-llm gpt-oss-120b --skill car_domain_120b.md"

[config]
num_trials = 1
task_split = "train"
tasks_base_num_tasks = 0
tasks_hallucination_num_tasks = 1
tasks_hallucination_task_id_filter = ["hallucination_92"]
tasks_disambiguation_num_tasks = 0
max_steps = 50

user_model = "gemini/gemini-2.5-flash"
user_provider = "gemini"
user_thinking = false

policy_evaluator_model = "gemini/gemini-2.5-flash"
policy_evaluator_provider = "gemini"
